// Generated from docs/TERMS.md — keep the two in sync and bump
// TERMS_VERSION here AND in src-tauri/src/models.rs on material changes
// (users are re-prompted to accept).

export const TERMS_VERSION = 2;

export const TERMS_MD = `# Qivreno Terms & Conditions

**Version 1.0 — Effective July 8, 2026**
**272 Solutions LLC**

## 1. Acceptance of Terms

By clicking "I Agree," installing, or using the Qivreno application ("the Software"), you agree to be bound by these Terms & Conditions ("Terms"). If you do not agree, do not use the Software. If you are using the Software on behalf of a business, you represent that you have authority to bind that business, and "you" refers to that business.

## 2. The Software

Qivreno is a desktop application published by 272 Solutions LLC ("272 Solutions," "we," "us") that lets you create and operate AI agents which generate text, documents, and other content, communicate with each other, and — with permissions you grant — read and write files and take actions on your computer and connected services.

## 3. AI-GENERATED CONTENT DISCLAIMER

**ALL RESPONSES, DOCUMENTS, ANALYSES, RECOMMENDATIONS, AND OTHER OUTPUT PRODUCED BY AGENTS IN THE SOFTWARE ARE GENERATED BY ARTIFICIAL INTELLIGENCE.** AI-generated content:

- **Is provided for reference and informational purposes only.**
- May be inaccurate, incomplete, outdated, biased, or entirely fabricated, even when it appears confident, detailed, or authoritative.
- **Is not professional advice.** Output is not, and must not be relied upon as, legal, financial, accounting, tax, investment, medical, safety, engineering, or other professional advice. Agents with role names such as "Legal," "Accounting," "HR," "Compliance," or similar are labels for organizing AI assistance — they are not licensed professionals, and their output is not a substitute for consulting one.
- **Must be independently verified by you before you rely or act on it.** You are solely responsible for reviewing, verifying, and approving all AI output before using it in your business or providing it to any third party.

**YOU ASSUME ALL RISK ARISING FROM YOUR USE OF, OR RELIANCE ON, AI-GENERATED OUTPUT. 272 SOLUTIONS SHALL HAVE NO LIABILITY FOR ANY LOSS, DAMAGE, COST, OR CONSEQUENCE RESULTING FROM AI-GENERATED OUTPUT, INCLUDING FAULTY, INACCURATE, OR MISLEADING ANSWERS, OR FROM DECISIONS MADE OR ACTIONS TAKEN IN RELIANCE ON SUCH OUTPUT.**

## 4. Autonomous Agents and Your Responsibility

The Software allows agents to act autonomously, including creating and modifying files, running commands (when you grant "Full access"), exchanging messages, and — where configured — communicating with external services. You acknowledge and agree that:

- You choose the permissions each agent receives, and you are responsible for the consequences of those choices.
- Actions taken by agents on your systems, data, accounts, and communications are deemed actions taken by you.
- You are responsible for supervising agent activity and for any content agents create or send, including its accuracy, legality, and suitability.
- You will maintain appropriate backups of your data.

## 5. License, Trial, and Subscription

Subject to these Terms and payment of applicable fees, 272 Solutions grants you a limited, non-exclusive, non-transferable license to install and use the Software for your internal business purposes. New installations include a limited free trial. Continued use requires a valid subscription license key. Keys may not be shared, resold, or used beyond their seat count. When a subscription lapses, the Software limits agent execution but does not delete your data. Fees are non-refundable except where required by law.

## 6. Third-Party AI Services

The Software can connect to third-party AI providers and tools you supply (for example: Anthropic Claude, OpenAI Codex, Ollama, LM Studio, and models such as Qwen). Your use of those providers is governed by their own terms and pricing, is your responsibility, and is outside our control. We do not guarantee availability, performance, or output quality of any third-party model or service. Local models run entirely on your hardware; their output is subject to the same disclaimer in Section 3.

## 7. Your Data

The Software stores your data (agents, tasks, messages, documents, memory, settings) locally on your computer. We do not operate servers that receive your content, and we cannot recover data you lose. You are responsible for the lawfulness of the data you process with the Software, including any personal data of others.

## 8. Acceptable Use

You will not use the Software to violate any law; to infringe others' rights; to generate or distribute malicious code; to send spam or deceptive communications; or to misrepresent AI-generated content as human-authored where the law requires disclosure. You will not reverse engineer the Software except where permitted by law, and you will not circumvent license enforcement.

## 9. Intellectual Property

The Software is licensed, not sold. 272 Solutions retains all rights in the Software and the Qivreno brand. As between you and 272 Solutions, you own the output your agents generate, subject to any rights of the third-party model providers under their terms.

## 10. DISCLAIMER OF WARRANTIES

**THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR UNINTERRUPTED OPERATION. WE DO NOT WARRANT THAT AI OUTPUT WILL BE ACCURATE, RELIABLE, OR SUITABLE FOR ANY PURPOSE.**

## 11. LIMITATION OF LIABILITY

**TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) 272 SOLUTIONS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST DATA, BUSINESS INTERRUPTION, OR REPUTATIONAL HARM, ARISING FROM OR RELATING TO THE SOFTWARE OR AI-GENERATED OUTPUT, EVEN IF ADVISED OF THE POSSIBILITY; AND (B) 272 SOLUTIONS' TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS SHALL NOT EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS (USD $100) OR THE FEES YOU PAID FOR THE SOFTWARE IN THE TWELVE (12) MONTHS BEFORE THE CLAIM AROSE.** Some jurisdictions do not allow certain limitations; in those jurisdictions, these limits apply to the fullest extent permitted.

## 12. Indemnification

You will indemnify and hold harmless 272 Solutions from claims, damages, and expenses (including reasonable attorneys' fees) arising from your use of the Software, agent actions performed under your permissions, your data, or your violation of these Terms.

## 13. Changes to the Software and Terms

We may update the Software and these Terms. Material changes to the Terms will be presented in the application for renewed acceptance. Continued use after acceptance of updated Terms constitutes agreement.

## 14. Termination

You may stop using the Software at any time. We may terminate or suspend your license for breach of these Terms. Sections 3, 4, and 9–12 survive termination.

## 15. Governing Law

These Terms are governed by the laws of the State of North Carolina, without regard to conflict-of-law rules. Exclusive venue lies in the state and federal courts located there.

## 16. Contact

272 Solutions LLC — questions about these Terms: contact the publisher at the address provided at purchase.
`;
